### ISSUE TITLE
Quadro de participações do foco 1.

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_02#10]
Realizar o quadro de participação do foco 1, com versionamento padronizado.

Obs.: Deixar voto de significância para o deadline da segunda entrega.

**Comment by claudiohsc** [comment]
Lembrar de verificar TEAMATES essa sprint ainda

**Comment by pabloheika** [comment]
> Lembrar de verificar TEAMATES essa sprint ainda

Foi liberado meu usuário.

**Comment by pabloheika** [comment]
Todos os integrantes já podem preencher as suas participações no foco 1 na planilha compartilhada com os integrantes.
