### ISSUE TITLE
Diagrama de Atividades

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_02#13]
Realizar o Diagrama de Atividades do projeto.

- [x] Colocar na issue a gravação da realização.
- [x] Colocar a modelagem em assets dentro da pasta modelagem com os co-authors nos commits.
- [x] Documentar o artefato seguindo o template para documentos #4.

**Comment by JoelSRangel** [comment]
[Blank diagram.pdf](https://github.com/user-attachments/files/17807755/Blank.diagram.pdf)
O diagrama de atividades foi feito através do lucidchart no dia 18/11 em uma reunião no microsoft teams

**Comment by JoelSRangel** [comment]
Gravação da confecção disponível em: https://youtu.be/NSocxGJ7qnk?si=VhpE4N1fcM_L0vSo
