### ISSUE TITLE
Diagrama de Comunicação/Colaboração

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_02#14]
Realizar os Diagrama de Comunicação/Colaboração do projeto.

- [x] Colocar na issue a gravação da realização.
- [x] Colocar a modelagem em assets dentro da pasta modelagem com os co-authors nos commits.
- [x] Documentar o artefato seguindo o template para documentos #4.

**Comment by gmeister18** [comment]
![Diagrama de Colaboração_Comunicação (1)](https://github.com/user-attachments/assets/c6a27c95-bb9c-4ed8-9a78-7ce9a87ea880)

Segue o link da gravação do digrama de colaboração do processo de login e visualização de festa [Link](https://youtu.be/1ad-hU5JDbc)

**Comment by freitasc** [comment]
Criei o documento, mas falta mais casos de fluxos de comunicação

**Comment by gmeister18** [comment]
![Diagrama em branco](https://github.com/user-attachments/assets/817597e2-d160-4b44-b7ed-7a226a8c87e6)
![Diagrama em branco (1)](https://github.com/user-attachments/assets/b1c1c5a7-a675-400d-9a12-ae4438ba3ba3)
Diagramas realizados junto com @freitasc @pedro-rodiguero

**Comment by gmeister18** [comment]
reunião disponível em: [reunião](https://youtu.be/uQBXBZH6VxA)
