### ISSUE TITLE
Diagrama de Estados

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_02#15]
Realizar os Diagrama de Estados do projeto.

- [x] Colocar na issue a gravação da realização.
- [x] Colocar a modelagem em assets dentro da pasta modelagem com os co-authors nos commits.
- [ ] Documentar o artefato seguindo o template para documentos #4.

**Comment by TalesRG** [comment]
https://lucid.app/lucidchart/8c259d43-49b0-4079-a0ac-e3dd1977e482/edit?viewport_loc=-2002%2C-1402%2C7172%2C3491%2C0_0&invitationId=inv_882a26d1-6e69-40d1-b45f-3a46126098a9
![Diagrama em branco](https://github.com/user-attachments/assets/128b5cef-9af4-4d2f-912e-5fb55b0d8b35)

realizado por @TalesRG @analufernanndess @Pedrin0030

**Comment by TalesRG** [comment]
Link da reunião realizada : https://youtu.be/ogiKIaFY2oU
