### ISSUE TITLE
Diagrama de Pacotes

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_02#29]
Realizar os Diagrama de Pacotes do projeto.

- [x] Colocar na issue a gravação da realização.
- [x] Colocar a modelagem em assets dentro da pasta modelagem com os co-authors nos commits.
- [x] Documentar o artefato seguindo o template para documentos #4.

**Comment by claudiohsc** [comment]
No link segue a gravação da realização do Diagrama de Pacotes - EvenTour: [link da reunião](https://www.youtube.com/watch?v=AOnfNo4lcFQ)
Link do diagrama realizado: [Diagrama de Pacotes EvenTour](https://github.com/user-attachments/assets/8d9c0480-c904-4a38-a317-60ec2c0f5155)
