### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_02#3]
Realizar o Diagrama de Classes do projeto.

- [x] Colocar na issue a gravação da realização.
- [x] Colocar a modelagem em assets dentro da pasta modelagem com os co-authors nos commits.
- [x] Documentar o artefato seguindo o template para documentos #4.

**Comment by claudiohsc** [comment]
[Diagrama de Classes - EvenTour (2).pdf](https://github.com/user-attachments/files/17724252/Diagrama.de.Classes.-.EvenTour.2.pdf)

**Comment by claudiohsc** [comment]
Segue o link da gravação da realização do diagrama de classes: [reunião](https://www.youtube.com/watch?v=3HLaOY4Uw7w).
