### ISSUE TITLE
Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_02#30]
Realizar os Diagrama de Casos de Uso do projeto.

- [x] Colocar na issue a gravação da realização.
- [x] Colocar a modelagem em assets dentro da pasta modelagem com os co-authors nos commits.
- [x] Documentar o artefato seguindo o template para documentos #4.

**Comment by pabloheika** [comment]
![Diagrama-Casos-de-uso](https://github.com/user-attachments/assets/98ee3c04-faa3-47e3-ae03-71c7b479eb26)
Foi realizado a primeira versão do diagrama de caso de uso em [reunião](https://youtu.be/vMxy_ViBcKM) comigo, @EliasOliver21 e o @JoelSRangel .

**Comment by klmurussi** [comment]
Foi realizado o começo das especificações de caso de uso (de acordo com o diagrama) na [reunião](https://www.youtube.com/watch?v=yqhpW8xO2b8) comigo. @samuelalvess e @Pedrin0030
