### ISSUE TITLE
Criar Modelo de Artefato

### ISSUE THREAD

**Issue by claudiohsc** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_02#4]
Criar modelo markdown para os Artefatos da Entrega 2.

- [x] Introdução
- [x] Metodologia
- [x] Desenvolvimento
- [x] Referências/Bibliografia
- [x] Histórico de versões com detalhes

**Comment by pabloheika** [comment]
[TEMPLATE_DOC.md](https://github.com/user-attachments/files/17672947/TEMPLATE_DOC.md)
Criei um template para o grupo.

**Comment by claudiohsc** [comment]
Ok!
