### ISSUE TITLE
Diagrama de Implantação

### ISSUE THREAD

**Issue by pabloheika** [UnBArqDsw2024-2/2024.2_G5_Turismo_Entrega_02#8]
Realizar o Diagrama de Implantação do projeto.

- [x] Colocar na issue a gravação da realização.
- [x] Colocar a modelagem em assets dentro da pasta modelagem com os co-authors nos commits.
- [x] Documentar o artefato seguindo o template para documentos #4.

**Comment by samuelalvess** [comment]
![Diagrama de implantacao](https://github.com/user-attachments/assets/4d17d3da-c910-4be6-8d5a-14314ae5bbf8)
Foi realizado por @samuelalvess @gmeister18 @analufernanndess e a seguir o link da [reuniao](https://youtu.be/FpoC4CNPS9c) gravada!
